"""Unique Follow Request

Revision ID: 30db8f4c3549
Revises: b6a47f7f8218
Create Date: 2025-01-16 14:54:46.961681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '30db8f4c3549'
down_revision: Union[str, None] = 'b6a47f7f8218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('RequestSent', 'followersmodel', ['follower_id', 'following_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('RequestSent', 'followersmodel', type_='unique')
    # ### end Alembic commands ###
