"""report reason enum and unique constraints

Revision ID: 4c93a4e67e5b
Revises: 0ab0609205f7
Create Date: 2025-01-18 17:37:05.565515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '4c93a4e67e5b'
down_revision: Union[str, None] = '0ab0609205f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('LikedAlready', 'likes', ['liked_by', 'post_id'])
    op.alter_column('reportpost', 'reason',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Enum('SPAM', 'INAPPROPRIATE', 'HARASSMENT', 'COPYRIGHT', 'OTHER', name='reportreason'),
               nullable=True, postgresql_using="reason::reportreason")
    op.create_unique_constraint('ReportedOnce', 'reportpost', ['reported_by', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ReportedOnce', 'reportpost', type_='unique')
    op.alter_column('reportpost', 'reason',
               existing_type=sa.Enum('SPAM', 'INAPPROPRIATE', 'HARASSMENT', 'COPYRIGHT', 'OTHER', name='reportreason'),
               type_=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_constraint('LikedAlready', 'likes', type_='unique')
    # ### end Alembic commands ###
