"""password field constraint

Revision ID: 7393d63745ec
Revises: 2f5a295d6df9
Create Date: 2025-01-30 13:02:17.389759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7393d63745ec'
down_revision: Union[str, None] = '2f5a295d6df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_base_user_id', table_name='user')
    op.create_index(op.f('ix_user_base_user_id'), 'user', ['base_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_base_user_id'), table_name='user')
    op.create_index('ix_user_base_user_id', 'user', ['base_user_id'], unique=False)
    # ### end Alembic commands ###
