"""creating indexes for user models

Revision ID: cc524edfdba6
Revises: db30fb0dfaa6
Create Date: 2025-01-21 10:21:24.677948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'cc524edfdba6'
down_revision: Union[str, None] = 'db30fb0dfaa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_base_user_id'), 'admin', ['base_user_id'], unique=False)
    op.drop_constraint('baseuser_email_key', 'baseuser', type_='unique')
    op.create_index(op.f('ix_baseuser_email'), 'baseuser', ['email'], unique=True)
    op.drop_constraint('otp_base_user_id_key', 'otp', type_='unique')
    op.create_index(op.f('ix_otp_base_user_id'), 'otp', ['base_user_id'], unique=True)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_base_user_id'), 'user', ['base_user_id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_base_user_id'), table_name='user')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_index(op.f('ix_otp_base_user_id'), table_name='otp')
    op.create_unique_constraint('otp_base_user_id_key', 'otp', ['base_user_id'])
    op.drop_index(op.f('ix_baseuser_email'), table_name='baseuser')
    op.create_unique_constraint('baseuser_email_key', 'baseuser', ['email'])
    op.drop_index(op.f('ix_admin_base_user_id'), table_name='admin')
    # ### end Alembic commands ###
