"""Update Relationships for BaseUser, User, Admin

Revision ID: cf078f0a3a00
Revises: 692e6d3148f2
Create Date: 2025-01-08 11:44:16.288172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'cf078f0a3a00'
down_revision: Union[str, None] = '692e6d3148f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('base_user_id', sa.Uuid(), nullable=False))
    op.drop_constraint('admin_user_id_fkey', 'admin', type_='foreignkey')
    op.create_foreign_key(None, 'admin', 'baseuser', ['base_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('admin', 'user_id')
    op.add_column('user', sa.Column('base_user_id', sa.Uuid(), nullable=False))
    op.drop_constraint('user_user_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'baseuser', ['base_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_user_id_fkey', 'user', 'baseuser', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'base_user_id')
    op.add_column('admin', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.create_foreign_key('admin_user_id_fkey', 'admin', 'baseuser', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('admin', 'base_user_id')
    # ### end Alembic commands ###
