"""otp update

Revision ID: db30fb0dfaa6
Revises: 4c93a4e67e5b
Create Date: 2025-01-18 19:10:32.089562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'db30fb0dfaa6'
down_revision: Union[str, None] = '4c93a4e67e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('base_user_id', sa.Uuid(), nullable=False))
    op.drop_constraint('otp_user_id_key', 'otp', type_='unique')
    op.create_unique_constraint(None, 'otp', ['base_user_id'])
    op.drop_constraint('otp_user_id_fkey', 'otp', type_='foreignkey')
    op.create_foreign_key(None, 'otp', 'baseuser', ['base_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('otp', 'otp_token')
    op.drop_column('otp', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('otp', sa.Column('otp_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'otp', type_='foreignkey')
    op.create_foreign_key('otp_user_id_fkey', 'otp', 'baseuser', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'otp', type_='unique')
    op.create_unique_constraint('otp_user_id_key', 'otp', ['user_id'])
    op.drop_column('otp', 'base_user_id')
    # ### end Alembic commands ###
