"""media update

Revision ID: e5c48cdc1aaa
Revises: 4c962aa0d8a8
Create Date: 2025-01-17 16:27:38.172690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5c48cdc1aaa'
down_revision: Union[str, None] = '4c962aa0d8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'media_url',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('media', 'media_type',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'media_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('media', 'media_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
